name: Deployment

on:
    push:
        branches: ["master"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  platforms: linux/amd64
            - name: Login to Docker Registry (Github Packages)
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Lowercase the repo name
              run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
                  file: ./Dockerfile
